// Offline generator for the tail of the campaign (levels 21-99).
//
// Nothing here runs in the browser: a level only reaches src/generated-levels.js after the real
// game loop has cleared it without damage, so every shipped level carries the same evidence the
// hand-authored opening does. Re-running with the same --seed reproduces the pool byte for byte.
import fs from 'node:fs';
import { createRuntime } from '../test/helpers/runtime.js';
import { generateLevel, levelIsSane } from './lib/level-gen.mjs';
import { solveLevel } from './lib/beam-solver.mjs';

const FIRST_INDEX = 20;    // levels 1-20 are hand-authored and already shipped
const TOTAL_LEVELS = 99;
// Turrets roughly triple the search depth the beam needs, because the route has to interleave with
// bullet timing. Measured: with 8000 nodes a turret level solved 0/8 regardless of difficulty tier;
// with 30000 it solved 8/8 at the same tier. Difficulty was never the blocker — budget was.
const NODE_BUDGET = 30000;

function parseArgs(argv) {
  const options = { count: TOTAL_LEVELS - FIRST_INDEX, seed: 20260911, offset: 0, probe: 0, quiet: false, json: null, merge: [] };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--count') options.count = Number(argv[++i]);
    else if (argv[i] === '--seed') options.seed = Number(argv[++i]);
    // Absolute index of this run's first level, so several shards can cover disjoint slices of the
    // curve while each still sees the spec its levels are supposed to have.
    else if (argv[i] === '--offset') options.offset = Number(argv[++i]);
    else if (argv[i] === '--probe') options.probe = Number(argv[++i]);
    else if (argv[i] === '--json') options.json = argv[++i];
    // Consumes every following path, so `--merge a.json b.json c.json` works as written.
    else if (argv[i] === '--merge') { while (i + 1 < argv.length && !argv[i + 1].startsWith('--')) options.merge.push(argv[++i]); }
    else if (argv[i] === '--quiet') options.quiet = true;
  }
  return options;
}

function writeModule(entries) {
  const banner = `// Generated by scripts/gen-levels.mjs. Do not edit by hand: every entry was cleared without\n`
    + '// damage through the real game loop before it was written here.\n';
  const body = `export const GENERATED_LEVELS = ${JSON.stringify(entries.map(entry => entry.level), null, 2)};\n\n`
    + `export const GENERATED_ROUTES = ${JSON.stringify(entries.map(entry => entry.route), null, 2)};\n`;
  fs.writeFileSync('src/generated-levels.js', banner + body);
  process.stderr.write(`已写入 src/generated-levels.js（${entries.length} 关，第 ${FIRST_INDEX + 1}–${FIRST_INDEX + entries.length} 关）\n`);
}

// The tail starts where the hand-authored climax left off (F20 is 7 guards + 4 chips) rather than
// dropping back to a two-room warm-up, then climbs to roughly double that by level 99.
const NAMES = ['断线', '静区', '折返', '夹层', '暗门', '盲区', '断层', '回环', '窄门', '落点', '过载', '切角'];
function specFor(index, id, levelNumber) {
  const t = index / Math.max(1, TOTAL_LEVELS - FIRST_INDEX - 1);
  const tier = 20 + t * 25;
  return {
    id, name: `${NAMES[levelNumber % NAMES.length]} ${levelNumber}`, code: `${levelNumber} / DEEP`,
    difficulty: 1 + tier / 4.2, difficultyTier: tier,
    // Caps kept near F20's scale (12 objectives): past that the solver almost never finds a
    // damage-free route inside its node budget, so those candidates are pure wasted compute.
    hunters: 3 + Math.round(t * 1),
    turrets: Math.round(t * 2),
    armored: Math.round(t * 1),
    chips: 2 + Math.round(t * 1),
    walls: 2 + Math.round(t * 2),
  };
}

const options = parseArgs(process.argv.slice(2));

// Merge mode: stitch the shards back together in level order. Running the search in four
// processes instead of one is the difference between a 20-minute job and an 80-minute one.
if (options.merge.length) {
  const entries = options.merge
    .flatMap(path => JSON.parse(fs.readFileSync(path, 'utf8')))
    .sort((a, b) => a.level.id.localeCompare(b.level.id));
  const expected = TOTAL_LEVELS - FIRST_INDEX;
  if (entries.length !== expected) process.stderr.write(`警告：合并得到 ${entries.length} 关，预期 ${expected} 关\n`);
  writeModule(entries);
  if (entries.length !== expected) process.exitCode = 1;
  process.exit();
}

const game = createRuntime();
const verifier = createRuntime();
const rejects = new Map();
const levels = [];
const started = Date.now();

const attempts = options.probe || options.count * 60;
for (let seed = options.seed; levels.length < options.count && seed < options.seed + attempts; seed += 1) {
  const index = options.offset + levels.length;
  const levelNumber = FIRST_INDEX + index + 1;
  const spec = specFor(index, `d${levelNumber}`, levelNumber);
  spec.enemies = spec.hunters + spec.turrets + spec.armored;
  const generated = generateLevel(seed, spec);
  if (generated.rejected) { rejects.set(generated.rejected, (rejects.get(generated.rejected) ?? 0) + 1); continue; }
  const { level, route } = generated;
  if (!levelIsSane(level)) { rejects.set('insane', (rejects.get('insane') ?? 0) + 1); continue; }

  let outcome = null;
  // Fast path, only when the intended line is still walkable: replay it and see.
  if (!generated.intendedBlocked) {
    game.startLevelData(level);
    for (const [x, y] of route) { game.touch(x, y, 0.7); game.step(0.08); }
    if (game.state.mode === 'floorClear' && game.state.floorHits === 0) outcome = { route, moves: game.state.floorMoves };
  }
  if (!outcome) {
    // Slow path: walls are in the way, or the level has turrets or armour. Pay for a search.
    game.startLevelData(level);
    const solved = solveLevel(game, { maxNodes: NODE_BUDGET });
    if (solved.solved) outcome = { route: solved.route, moves: solved.moves };
  }
  if (!outcome) { rejects.set('unplayable', (rejects.get('unplayable') ?? 0) + 1); continue; }

  level.parMoves = outcome.moves;
  // Independent re-check on a fresh runtime, so a stale-state artefact cannot sneak a level through.
  verifier.startLevelData(level);
  for (const [x, y] of outcome.route) { verifier.touch(x, y, 0.7); verifier.step(0.08); }
  if (verifier.state.mode !== 'floorClear' || verifier.state.floorHits !== 0) { rejects.set('recheck-failed', (rejects.get('recheck-failed') ?? 0) + 1); continue; }

  levels.push({ level, route: outcome.route });
  if (!options.quiet) process.stderr.write(`${level.id}: ${outcome.moves} moves, tier ${level.difficultyTier.toFixed(0)}, seed ${seed}\n`);
}

const total = levels.length + [...rejects.values()].reduce((sum, n) => sum + n, 0);
process.stderr.write(`\n接受 ${levels.length} 关 / 尝试 ${total} 次 (${total ? Math.round(levels.length / total * 100) : 0}%)，用时 ${((Date.now() - started) / 1000).toFixed(1)}s\n`);
for (const [reason, count] of [...rejects].sort((a, b) => b[1] - a[1])) process.stderr.write(`  拒绝 ${reason}: ${count}\n`);

if (options.json) {
  fs.writeFileSync(options.json, JSON.stringify(levels));
  process.stderr.write(`已写入 ${options.json}（${levels.length} 关）\n`);
} else {
  writeModule(levels);
}
if (levels.length < options.count) process.exitCode = 1;
