// Offline level generator for the daily challenge and endless mode.
//
// Nothing here runs in the browser: a level only reaches src/daily-levels.js after the real game
// loop has cleared it without taking damage, so every shipped level carries the same evidence the
// handcrafted campaign does. Re-running with the same --seed reproduces the pool byte for byte.
import fs from 'node:fs';
import { createRuntime } from '../test/helpers/runtime.js';
import { generateLevel, levelIsSane } from './lib/level-gen.mjs';
import { solveLevel } from './lib/beam-solver.mjs';

const POOL_SIZE = 90;      // roughly three months of daily challenges before the pool repeats
const NODE_BUDGET = 6000;  // ~3s of search before a candidate is abandoned

function parseArgs(argv) {
  const options = { count: POOL_SIZE, seed: 20260911, probe: 0, quiet: false };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--count') options.count = Number(argv[++i]);
    else if (argv[i] === '--seed') options.seed = Number(argv[++i]);
    else if (argv[i] === '--probe') options.probe = Number(argv[++i]);
    else if (argv[i] === '--quiet') options.quiet = true;
  }
  return options;
}

// Difficulty is spread across the pool so the daily rotation does not serve the same pressure
// every day. `difficultyTier` is what main.js reads for enemy speed and turret cadence.
function specFor(index, id) {
  const tier = 4 + (index * 7) % 13;
  const enemies = 2 + (index % 4);
  const chips = 1 + (index % 3);
  return {
    id, name: `每日 ${String(index + 1).padStart(2, '0')}`, code: `${String(index + 1).padStart(2, '0')} / DAILY`,
    difficulty: Math.round((tier / 4) * 10) / 10, difficultyTier: tier,
    enemies, chips, walls: 1 + (index % 3),
  };
}

const options = parseArgs(process.argv.slice(2));
const game = createRuntime();
const verifier = createRuntime();
const rejects = new Map();
const levels = [];
const started = Date.now();

const attempts = options.probe || options.count * 40;
for (let seed = options.seed; levels.length < options.count && seed < options.seed + attempts; seed += 1) {
  const index = levels.length;
  const generated = generateLevel(seed, specFor(index, `d${String(index + 1).padStart(3, '0')}`));
  if (generated.rejected) { rejects.set(generated.rejected, (rejects.get(generated.rejected) ?? 0) + 1); continue; }
  const { level, route } = generated;
  if (!levelIsSane(level)) { rejects.set('insane', (rejects.get('insane') ?? 0) + 1); continue; }

  // Fast path: replay the route the generator had in mind.
  game.startLevelData(level);
  let outcome = null;
  for (const [x, y] of route) { game.touch(x, y, 0.7); game.step(0.08); }
  if (game.state.mode === 'floorClear' && game.state.floorHits === 0) outcome = { route, moves: game.state.floorMoves };
  else {
    // Slow path: let the shared solver look for any damage-free route at all.
    game.startLevelData(level);
    const solved = solveLevel(game, { maxNodes: NODE_BUDGET });
    if (solved.solved) outcome = { route: solved.route, moves: solved.moves };
  }
  if (!outcome) { rejects.set('unplayable', (rejects.get('unplayable') ?? 0) + 1); continue; }

  level.parMoves = outcome.moves;
  // Independent re-check on a fresh runtime, so a stale-state artefact cannot sneak a level through.
  verifier.startLevelData(level);
  for (const [x, y] of outcome.route) { verifier.touch(x, y, 0.7); verifier.step(0.08); }
  if (verifier.state.mode !== 'floorClear' || verifier.state.floorHits !== 0) { rejects.set('recheck-failed', (rejects.get('recheck-failed') ?? 0) + 1); continue; }

  levels.push({ level, route: outcome.route });
  if (!options.quiet) process.stderr.write(`${level.id}: ${outcome.moves} moves, seed ${seed}\n`);
}

const total = levels.length + [...rejects.values()].reduce((sum, n) => sum + n, 0);
process.stderr.write(`\n接受 ${levels.length} 关 / 尝试 ${total} 次 (${total ? Math.round(levels.length / total * 100) : 0}%)，用时 ${((Date.now() - started) / 1000).toFixed(1)}s\n`);
for (const [reason, count] of [...rejects].sort((a, b) => b[1] - a[1])) process.stderr.write(`  拒绝 ${reason}: ${count}\n`);

const banner = `// Generated by scripts/gen-daily.mjs --seed ${options.seed}. Do not edit by hand: every entry was\n`
  + '// cleared without damage through the real game loop before it was written here.\n';
const body = `export const DAILY_LEVELS = ${JSON.stringify(levels.map(entry => entry.level), null, 2)};\n\n`
  + `export const DAILY_ROUTES = ${JSON.stringify(levels.map(entry => entry.route), null, 2)};\n`;
fs.mkdirSync('src', { recursive: true });
fs.writeFileSync('src/daily-levels.js', banner + body);
process.stderr.write(`已写入 src/daily-levels.js（${levels.length} 关）\n`);
if (levels.length < options.count) process.exitCode = 1;
