// Generated by scripts/gen-daily.mjs --seed 20260911. Do not edit by hand: every entry was
// cleared without damage through the real game loop before it was written here.
export const DAILY_LEVELS = [
  {
    "id": "d001",
    "name": "每日 01",
    "code": "01 / DAILY",
    "difficulty": 1,
    "difficultyTier": 4,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      240,
      1112
    ],
    "portal": [
      195,
      335
    ],
    "chips": [
      [
        157,
        726
      ]
    ],
    "enemies": [
      [
        "hunter",
        80,
        532
      ],
      [
        "hunter",
        123,
        936
      ]
    ],
    "walls": [
      [
        248,
        282,
        42,
        359
      ]
    ],
    "items": []
  },
  {
    "id": "d002",
    "name": "每日 02",
    "code": "02 / DAILY",
    "difficulty": 2.8,
    "difficultyTier": 11,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      370,
      1106
    ],
    "portal": [
      529,
      178
    ],
    "chips": [
      [
        577,
        644
      ],
      [
        551,
        272
      ]
    ],
    "enemies": [
      [
        "hunter",
        394,
        726
      ],
      [
        "hunter",
        303,
        937
      ],
      [
        "hunter",
        658,
        438
      ]
    ],
    "walls": [
      [
        418,
        1088,
        196,
        42
      ],
      [
        184,
        219,
        182,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d003",
    "name": "每日 03",
    "code": "03 / DAILY",
    "difficulty": 1.3,
    "difficultyTier": 5,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      554,
      1110
    ],
    "portal": [
      138,
      310
    ],
    "chips": [
      [
        344,
        202
      ],
      [
        566,
        267
      ],
      [
        608,
        895
      ]
    ],
    "enemies": [
      [
        "hunter",
        159,
        282
      ],
      [
        "hunter",
        653,
        490
      ],
      [
        "hunter",
        609,
        702
      ],
      [
        "hunter",
        64,
        472
      ]
    ],
    "walls": [
      [
        111,
        777,
        319,
        42
      ],
      [
        155,
        385,
        42,
        352
      ],
      [
        100,
        899,
        408,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d004",
    "name": "每日 04",
    "code": "04 / DAILY",
    "difficulty": 3,
    "difficultyTier": 12,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      226,
      1064
    ],
    "portal": [
      240,
      178
    ],
    "chips": [
      [
        643,
        574
      ]
    ],
    "enemies": [
      [
        "hunter",
        313,
        850
      ],
      [
        "hunter",
        463,
        206
      ],
      [
        "hunter",
        579,
        348
      ],
      [
        "hunter",
        235,
        214
      ],
      [
        "hunter",
        538,
        765
      ]
    ],
    "walls": [
      [
        60,
        1111,
        317,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d005",
    "name": "每日 05",
    "code": "05 / DAILY",
    "difficulty": 1.5,
    "difficultyTier": 6,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      451,
      1138
    ],
    "portal": [
      650,
      256
    ],
    "chips": [
      [
        645,
        470
      ],
      [
        363,
        918
      ]
    ],
    "enemies": [
      [
        "hunter",
        523,
        624
      ],
      [
        "hunter",
        393,
        735
      ]
    ],
    "walls": [
      [
        231,
        516,
        42,
        348
      ],
      [
        495,
        729,
        42,
        263
      ]
    ],
    "items": []
  },
  {
    "id": "d006",
    "name": "每日 06",
    "code": "06 / DAILY",
    "difficulty": 3.3,
    "difficultyTier": 13,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      412,
      1139
    ],
    "portal": [
      459,
      178
    ],
    "chips": [
      [
        520,
        279
      ],
      [
        187,
        343
      ],
      [
        102,
        560
      ]
    ],
    "enemies": [
      [
        "hunter",
        325,
        229
      ],
      [
        "hunter",
        314,
        919
      ],
      [
        "hunter",
        187,
        754
      ]
    ],
    "walls": [
      [
        613,
        482,
        42,
        351
      ],
      [
        271,
        371,
        382,
        42
      ],
      [
        145,
        851,
        42,
        203
      ]
    ],
    "items": []
  },
  {
    "id": "d007",
    "name": "每日 07",
    "code": "07 / DAILY",
    "difficulty": 1.8,
    "difficultyTier": 7,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      626,
      1135
    ],
    "portal": [
      213,
      178
    ],
    "chips": [
      [
        575,
        915
      ]
    ],
    "enemies": [
      [
        "hunter",
        529,
        734
      ],
      [
        "hunter",
        181,
        278
      ],
      [
        "hunter",
        501,
        507
      ],
      [
        "hunter",
        392,
        334
      ]
    ],
    "walls": [
      [
        581,
        320,
        42,
        286
      ]
    ],
    "items": []
  },
  {
    "id": "d008",
    "name": "每日 08",
    "code": "08 / DAILY",
    "difficulty": 3.5,
    "difficultyTier": 14,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      576,
      1063
    ],
    "portal": [
      449,
      178
    ],
    "chips": [
      [
        467,
        914
      ],
      [
        64,
        556
      ]
    ],
    "enemies": [
      [
        "hunter",
        60,
        357
      ],
      [
        "hunter",
        352,
        735
      ],
      [
        "hunter",
        395,
        191
      ],
      [
        "hunter",
        184,
        679
      ],
      [
        "hunter",
        213,
        191
      ]
    ],
    "walls": [
      [
        233,
        596,
        287,
        42
      ],
      [
        205,
        498,
        399,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d009",
    "name": "每日 09",
    "code": "09 / DAILY",
    "difficulty": 2,
    "difficultyTier": 8,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      505,
      1133
    ],
    "portal": [
      650,
      178
    ],
    "chips": [
      [
        649,
        393
      ],
      [
        654,
        199
      ],
      [
        407,
        967
      ]
    ],
    "enemies": [
      [
        "hunter",
        492,
        750
      ],
      [
        "hunter",
        489,
        542
      ]
    ],
    "walls": [
      [
        551,
        1015,
        42,
        272
      ],
      [
        237,
        685,
        42,
        274
      ],
      [
        144,
        872,
        42,
        274
      ]
    ],
    "items": []
  },
  {
    "id": "d010",
    "name": "每日 10",
    "code": "10 / DAILY",
    "difficulty": 3.8,
    "difficultyTier": 15,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      451,
      1075
    ],
    "portal": [
      138,
      182
    ],
    "chips": [
      [
        93,
        604
      ]
    ],
    "enemies": [
      [
        "hunter",
        190,
        395
      ],
      [
        "hunter",
        341,
        896
      ],
      [
        "hunter",
        138,
        794
      ]
    ],
    "walls": [
      [
        566,
        964,
        42,
        204
      ]
    ],
    "items": []
  },
  {
    "id": "d011",
    "name": "每日 11",
    "code": "11 / DAILY",
    "difficulty": 2.3,
    "difficultyTier": 9,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      361,
      1087
    ],
    "portal": [
      394,
      178
    ],
    "chips": [
      [
        174,
        513
      ],
      [
        297,
        189
      ]
    ],
    "enemies": [
      [
        "hunter",
        499,
        190
      ],
      [
        "hunter",
        157,
        313
      ],
      [
        "hunter",
        304,
        868
      ],
      [
        "hunter",
        319,
        649
      ]
    ],
    "walls": [
      [
        65,
        230,
        42,
        273
      ],
      [
        122,
        824,
        42,
        407
      ]
    ],
    "items": []
  },
  {
    "id": "d012",
    "name": "每日 12",
    "code": "12 / DAILY",
    "difficulty": 4,
    "difficultyTier": 16,
    "tutorial": false,
    "brief": "",
    "parMoves": 9,
    "start": [
      402,
      1145
    ],
    "portal": [
      156,
      466
    ],
    "chips": [
      [
        208,
        222
      ],
      [
        65,
        416
      ],
      [
        127,
        640
      ]
    ],
    "enemies": [
      [
        "hunter",
        496,
        939
      ],
      [
        "hunter",
        617,
        746
      ],
      [
        "hunter",
        624,
        543
      ],
      [
        "hunter",
        548,
        342
      ],
      [
        "hunter",
        393,
        216
      ]
    ],
    "walls": [
      [
        316,
        470,
        194,
        42
      ],
      [
        278,
        628,
        215,
        42
      ],
      [
        37,
        756,
        174,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d013",
    "name": "每日 13",
    "code": "13 / DAILY",
    "difficulty": 2.5,
    "difficultyTier": 10,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      526,
      1086
    ],
    "portal": [
      310,
      417
    ],
    "chips": [
      [
        259,
        580
      ]
    ],
    "enemies": [
      [
        "hunter",
        577,
        846
      ],
      [
        "hunter",
        483,
        634
      ]
    ],
    "walls": [
      [
        409,
        335,
        42,
        242
      ]
    ],
    "items": []
  },
  {
    "id": "d014",
    "name": "每日 14",
    "code": "14 / DAILY",
    "difficulty": 1,
    "difficultyTier": 4,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      467,
      1092
    ],
    "portal": [
      198,
      178
    ],
    "chips": [
      [
        191,
        243
      ],
      [
        531,
        663
      ]
    ],
    "enemies": [
      [
        "hunter",
        391,
        281
      ],
      [
        "hunter",
        516,
        480
      ],
      [
        "hunter",
        485,
        846
      ]
    ],
    "walls": [
      [
        389,
        624,
        42,
        303
      ],
      [
        334,
        375,
        42,
        217
      ]
    ],
    "items": []
  },
  {
    "id": "d015",
    "name": "每日 15",
    "code": "15 / DAILY",
    "difficulty": 2.8,
    "difficultyTier": 11,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      259,
      1111
    ],
    "portal": [
      178,
      178
    ],
    "chips": [
      [
        405,
        199
      ],
      [
        171,
        216
      ],
      [
        588,
        466
      ]
    ],
    "enemies": [
      [
        "hunter",
        651,
        705
      ],
      [
        "hunter",
        556,
        281
      ],
      [
        "hunter",
        518,
        882
      ],
      [
        "hunter",
        326,
        943
      ]
    ],
    "walls": [
      [
        136,
        756,
        269,
        42
      ],
      [
        173,
        264,
        42,
        245
      ],
      [
        124,
        948,
        42,
        180
      ]
    ],
    "items": []
  },
  {
    "id": "d016",
    "name": "每日 16",
    "code": "16 / DAILY",
    "difficulty": 1.3,
    "difficultyTier": 5,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      447,
      1064
    ],
    "portal": [
      70,
      178
    ],
    "chips": [
      [
        488,
        326
      ]
    ],
    "enemies": [
      [
        "hunter",
        567,
        888
      ],
      [
        "hunter",
        306,
        211
      ],
      [
        "hunter",
        509,
        510
      ],
      [
        "hunter",
        604,
        684
      ],
      [
        "hunter",
        83,
        243
      ]
    ],
    "walls": [
      [
        316,
        919,
        42,
        276
      ]
    ],
    "items": []
  },
  {
    "id": "d017",
    "name": "每日 17",
    "code": "17 / DAILY",
    "difficulty": 3,
    "difficultyTier": 12,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      160,
      1084
    ],
    "portal": [
      426,
      321
    ],
    "chips": [
      [
        513,
        512
      ],
      [
        323,
        579
      ]
    ],
    "enemies": [
      [
        "hunter",
        179,
        734
      ],
      [
        "hunter",
        84,
        903
      ]
    ],
    "walls": [
      [
        428,
        641,
        238,
        42
      ],
      [
        255,
        964,
        42,
        329
      ]
    ],
    "items": []
  },
  {
    "id": "d018",
    "name": "每日 18",
    "code": "18 / DAILY",
    "difficulty": 1.5,
    "difficultyTier": 6,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      414,
      1084
    ],
    "portal": [
      532,
      178
    ],
    "chips": [
      [
        240,
        225
      ],
      [
        78,
        540
      ],
      [
        149,
        375
      ]
    ],
    "enemies": [
      [
        "hunter",
        319,
        856
      ],
      [
        "hunter",
        124,
        717
      ],
      [
        "hunter",
        419,
        201
      ]
    ],
    "walls": [
      [
        620,
        709,
        42,
        258
      ],
      [
        219,
        544,
        394,
        42
      ],
      [
        242,
        305,
        211,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d019",
    "name": "每日 19",
    "code": "19 / DAILY",
    "difficulty": 3.3,
    "difficultyTier": 13,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      169,
      1072
    ],
    "portal": [
      70,
      178
    ],
    "chips": [
      [
        112,
        197
      ]
    ],
    "enemies": [
      [
        "hunter",
        359,
        537
      ],
      [
        "hunter",
        277,
        934
      ],
      [
        "hunter",
        282,
        303
      ],
      [
        "hunter",
        305,
        725
      ]
    ],
    "walls": [
      [
        369,
        857,
        42,
        320
      ]
    ],
    "items": []
  },
  {
    "id": "d020",
    "name": "每日 20",
    "code": "20 / DAILY",
    "difficulty": 1.8,
    "difficultyTier": 7,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      629,
      1063
    ],
    "portal": [
      70,
      283
    ],
    "chips": [
      [
        317,
        210
      ],
      [
        598,
        491
      ]
    ],
    "enemies": [
      [
        "hunter",
        474,
        284
      ],
      [
        "hunter",
        157,
        271
      ],
      [
        "hunter",
        613,
        851
      ],
      [
        "hunter",
        80,
        471
      ],
      [
        "hunter",
        526,
        664
      ]
    ],
    "walls": [
      [
        31,
        1048,
        420,
        42
      ],
      [
        503,
        805,
        42,
        211
      ]
    ],
    "items": []
  },
  {
    "id": "d021",
    "name": "每日 21",
    "code": "21 / DAILY",
    "difficulty": 3.5,
    "difficultyTier": 14,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      622,
      1111
    ],
    "portal": [
      70,
      178
    ],
    "chips": [
      [
        238,
        698
      ],
      [
        157,
        313
      ],
      [
        123,
        551
      ]
    ],
    "enemies": [
      [
        "hunter",
        495,
        962
      ],
      [
        "hunter",
        352,
        830
      ]
    ],
    "walls": [
      [
        608,
        790,
        42,
        237
      ],
      [
        73,
        969,
        257,
        42
      ],
      [
        194,
        358,
        200,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d022",
    "name": "每日 22",
    "code": "22 / DAILY",
    "difficulty": 2,
    "difficultyTier": 8,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      394,
      1134
    ],
    "portal": [
      113,
      178
    ],
    "chips": [
      [
        117,
        349
      ]
    ],
    "enemies": [
      [
        "hunter",
        185,
        511
      ],
      [
        "hunter",
        281,
        942
      ],
      [
        "hunter",
        171,
        746
      ]
    ],
    "walls": [
      [
        255,
        365,
        42,
        304
      ]
    ],
    "items": []
  },
  {
    "id": "d023",
    "name": "每日 23",
    "code": "23 / DAILY",
    "difficulty": 3.8,
    "difficultyTier": 15,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      199,
      1074
    ],
    "portal": [
      525,
      178
    ],
    "chips": [
      [
        465,
        192
      ],
      [
        134,
        338
      ]
    ],
    "enemies": [
      [
        "hunter",
        182,
        712
      ],
      [
        "hunter",
        234,
        890
      ],
      [
        "hunter",
        91,
        538
      ],
      [
        "hunter",
        241,
        205
      ]
    ],
    "walls": [
      [
        322,
        297,
        339,
        42
      ],
      [
        154,
        521,
        323,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d024",
    "name": "每日 24",
    "code": "24 / DAILY",
    "difficulty": 2.3,
    "difficultyTier": 9,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      631,
      1106
    ],
    "portal": [
      650,
      178
    ],
    "chips": [
      [
        290,
        916
      ],
      [
        160,
        773
      ],
      [
        294,
        199
      ]
    ],
    "enemies": [
      [
        "hunter",
        110,
        536
      ],
      [
        "hunter",
        654,
        200
      ],
      [
        "hunter",
        472,
        188
      ],
      [
        "hunter",
        488,
        950
      ],
      [
        "hunter",
        125,
        332
      ]
    ],
    "walls": [
      [
        370,
        376,
        42,
        360
      ],
      [
        217,
        404,
        42,
        175
      ],
      [
        56,
        719,
        42,
        225
      ]
    ],
    "items": []
  },
  {
    "id": "d025",
    "name": "每日 25",
    "code": "25 / DAILY",
    "difficulty": 4,
    "difficultyTier": 16,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      564,
      1120
    ],
    "portal": [
      461,
      335
    ],
    "chips": [
      [
        652,
        690
      ]
    ],
    "enemies": [
      [
        "hunter",
        567,
        485
      ],
      [
        "hunter",
        591,
        930
      ]
    ],
    "walls": [
      [
        431,
        1007,
        42,
        201
      ]
    ],
    "items": []
  },
  {
    "id": "d026",
    "name": "每日 26",
    "code": "26 / DAILY",
    "difficulty": 2.5,
    "difficultyTier": 10,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      443,
      1148
    ],
    "portal": [
      396,
      178
    ],
    "chips": [
      [
        589,
        805
      ],
      [
        420,
        284
      ]
    ],
    "enemies": [
      [
        "hunter",
        419,
        672
      ],
      [
        "hunter",
        596,
        993
      ],
      [
        "hunter",
        349,
        457
      ]
    ],
    "walls": [
      [
        82,
        216,
        247,
        42
      ],
      [
        335,
        968,
        42,
        323
      ]
    ],
    "items": []
  },
  {
    "id": "d027",
    "name": "每日 27",
    "code": "27 / DAILY",
    "difficulty": 1,
    "difficultyTier": 4,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      178,
      1111
    ],
    "portal": [
      311,
      178
    ],
    "chips": [
      [
        242,
        270
      ],
      [
        637,
        490
      ],
      [
        520,
        891
      ]
    ],
    "enemies": [
      [
        "hunter",
        316,
        946
      ],
      [
        "hunter",
        598,
        312
      ],
      [
        "hunter",
        633,
        735
      ],
      [
        "hunter",
        447,
        215
      ]
    ],
    "walls": [
      [
        394,
        393,
        42,
        194
      ],
      [
        153,
        812,
        42,
        216
      ],
      [
        60,
        519,
        219,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d028",
    "name": "每日 28",
    "code": "28 / DAILY",
    "difficulty": 2.8,
    "difficultyTier": 11,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      544,
      1136
    ],
    "portal": [
      497,
      178
    ],
    "chips": [
      [
        431,
        1003
      ]
    ],
    "enemies": [
      [
        "hunter",
        231,
        361
      ],
      [
        "hunter",
        409,
        242
      ],
      [
        "hunter",
        111,
        573
      ],
      [
        "hunter",
        246,
        937
      ],
      [
        "hunter",
        95,
        804
      ]
    ],
    "walls": [
      [
        383,
        858,
        252,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d029",
    "name": "每日 29",
    "code": "29 / DAILY",
    "difficulty": 1.3,
    "difficultyTier": 5,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      415,
      1084
    ],
    "portal": [
      269,
      199
    ],
    "chips": [
      [
        215,
        780
      ],
      [
        214,
        351
      ]
    ],
    "enemies": [
      [
        "hunter",
        185,
        562
      ],
      [
        "hunter",
        371,
        919
      ]
    ],
    "walls": [
      [
        618,
        380,
        42,
        274
      ],
      [
        495,
        922,
        42,
        213
      ]
    ],
    "items": []
  },
  {
    "id": "d030",
    "name": "每日 30",
    "code": "30 / DAILY",
    "difficulty": 3,
    "difficultyTier": 12,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      438,
      1092
    ],
    "portal": [
      70,
      256
    ],
    "chips": [
      [
        448,
        864
      ],
      [
        121,
        462
      ],
      [
        339,
        350
      ]
    ],
    "enemies": [
      [
        "hunter",
        648,
        543
      ],
      [
        "hunter",
        537,
        392
      ],
      [
        "hunter",
        632,
        729
      ]
    ],
    "walls": [
      [
        225,
        210,
        361,
        42
      ],
      [
        233,
        544,
        320,
        42
      ],
      [
        190,
        931,
        42,
        237
      ]
    ],
    "items": []
  },
  {
    "id": "d031",
    "name": "每日 31",
    "code": "31 / DAILY",
    "difficulty": 1.5,
    "difficultyTier": 6,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      593,
      1080
    ],
    "portal": [
      173,
      178
    ],
    "chips": [
      [
        532,
        869
      ]
    ],
    "enemies": [
      [
        "hunter",
        628,
        667
      ],
      [
        "hunter",
        628,
        445
      ],
      [
        "hunter",
        498,
        312
      ],
      [
        "hunter",
        293,
        212
      ]
    ],
    "walls": [
      [
        409,
        822,
        42,
        209
      ]
    ],
    "items": []
  },
  {
    "id": "d032",
    "name": "每日 32",
    "code": "32 / DAILY",
    "difficulty": 3.3,
    "difficultyTier": 13,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      292,
      1078
    ],
    "portal": [
      167,
      178
    ],
    "chips": [
      [
        488,
        228
      ],
      [
        534,
        800
      ]
    ],
    "enemies": [
      [
        "hunter",
        81,
        193
      ],
      [
        "hunter",
        338,
        912
      ],
      [
        "hunter",
        624,
        347
      ],
      [
        "hunter",
        320,
        190
      ],
      [
        "hunter",
        643,
        581
      ]
    ],
    "walls": [
      [
        293,
        509,
        42,
        294
      ],
      [
        182,
        692,
        42,
        402
      ]
    ],
    "items": []
  },
  {
    "id": "d033",
    "name": "每日 33",
    "code": "33 / DAILY",
    "difficulty": 1.8,
    "difficultyTier": 7,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      578,
      1132
    ],
    "portal": [
      207,
      178
    ],
    "chips": [
      [
        345,
        738
      ],
      [
        172,
        317
      ],
      [
        71,
        505
      ]
    ],
    "enemies": [
      [
        "hunter",
        144,
        659
      ],
      [
        "hunter",
        438,
        957
      ]
    ],
    "walls": [
      [
        334,
        458,
        355,
        42
      ],
      [
        489,
        604,
        42,
        215
      ],
      [
        470,
        857,
        180,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d034",
    "name": "每日 34",
    "code": "34 / DAILY",
    "difficulty": 3.5,
    "difficultyTier": 14,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      478,
      1072
    ],
    "portal": [
      453,
      178
    ],
    "chips": [
      [
        529,
        556
      ]
    ],
    "enemies": [
      [
        "hunter",
        473,
        891
      ],
      [
        "hunter",
        568,
        723
      ],
      [
        "hunter",
        467,
        339
      ]
    ],
    "walls": [
      [
        631,
        422,
        42,
        203
      ]
    ],
    "items": []
  },
  {
    "id": "d035",
    "name": "每日 35",
    "code": "35 / DAILY",
    "difficulty": 2,
    "difficultyTier": 8,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      534,
      1143
    ],
    "portal": [
      176,
      178
    ],
    "chips": [
      [
        461,
        989
      ],
      [
        63,
        207
      ]
    ],
    "enemies": [
      [
        "hunter",
        578,
        560
      ],
      [
        "hunter",
        445,
        374
      ],
      [
        "hunter",
        244,
        260
      ],
      [
        "hunter",
        534,
        752
      ]
    ],
    "walls": [
      [
        420,
        501,
        42,
        196
      ],
      [
        130,
        980,
        274,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d036",
    "name": "每日 36",
    "code": "36 / DAILY",
    "difficulty": 3.8,
    "difficultyTier": 15,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      418,
      1123
    ],
    "portal": [
      127,
      593
    ],
    "chips": [
      [
        595,
        574
      ],
      [
        489,
        904
      ],
      [
        522,
        356
      ]
    ],
    "enemies": [
      [
        "hunter",
        108,
        748
      ],
      [
        "hunter",
        168,
        360
      ],
      [
        "hunter",
        66,
        521
      ],
      [
        "hunter",
        603,
        761
      ],
      [
        "hunter",
        314,
        272
      ]
    ],
    "walls": [
      [
        220,
        386,
        42,
        187
      ],
      [
        208,
        877,
        42,
        336
      ],
      [
        121,
        994,
        42,
        338
      ]
    ],
    "items": []
  },
  {
    "id": "d037",
    "name": "每日 37",
    "code": "37 / DAILY",
    "difficulty": 2.3,
    "difficultyTier": 9,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      100,
      1095
    ],
    "portal": [
      321,
      333
    ],
    "chips": [
      [
        303,
        677
      ]
    ],
    "enemies": [
      [
        "hunter",
        346,
        498
      ],
      [
        "hunter",
        138,
        857
      ]
    ],
    "walls": [
      [
        187,
        947,
        42,
        273
      ]
    ],
    "items": []
  },
  {
    "id": "d038",
    "name": "每日 38",
    "code": "38 / DAILY",
    "difficulty": 4,
    "difficultyTier": 16,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      327,
      1094
    ],
    "portal": [
      402,
      178
    ],
    "chips": [
      [
        220,
        556
      ],
      [
        285,
        719
      ]
    ],
    "enemies": [
      [
        "hunter",
        343,
        354
      ],
      [
        "hunter",
        315,
        916
      ],
      [
        "hunter",
        502,
        202
      ]
    ],
    "walls": [
      [
        514,
        505,
        42,
        413
      ],
      [
        407,
        530,
        42,
        295
      ]
    ],
    "items": []
  },
  {
    "id": "d039",
    "name": "每日 39",
    "code": "39 / DAILY",
    "difficulty": 2.5,
    "difficultyTier": 10,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      451,
      1120
    ],
    "portal": [
      70,
      230
    ],
    "chips": [
      [
        580,
        440
      ],
      [
        71,
        421
      ],
      [
        229,
        319
      ]
    ],
    "enemies": [
      [
        "hunter",
        589,
        1016
      ],
      [
        "hunter",
        640,
        809
      ],
      [
        "hunter",
        613,
        619
      ],
      [
        "hunter",
        406,
        332
      ]
    ],
    "walls": [
      [
        484,
        599,
        42,
        293
      ],
      [
        87,
        472,
        42,
        356
      ],
      [
        171,
        1004,
        273,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d040",
    "name": "每日 40",
    "code": "40 / DAILY",
    "difficulty": 1,
    "difficultyTier": 4,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      407,
      1141
    ],
    "portal": [
      121,
      178
    ],
    "chips": [
      [
        585,
        595
      ]
    ],
    "enemies": [
      [
        "hunter",
        213,
        231
      ],
      [
        "hunter",
        420,
        229
      ],
      [
        "hunter",
        452,
        755
      ],
      [
        "hunter",
        545,
        364
      ],
      [
        "hunter",
        494,
        958
      ]
    ],
    "walls": [
      [
        247,
        1033,
        42,
        222
      ]
    ],
    "items": []
  },
  {
    "id": "d041",
    "name": "每日 41",
    "code": "41 / DAILY",
    "difficulty": 2.8,
    "difficultyTier": 11,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      255,
      1117
    ],
    "portal": [
      505,
      221
    ],
    "chips": [
      [
        494,
        570
      ],
      [
        377,
        956
      ]
    ],
    "enemies": [
      [
        "hunter",
        365,
        750
      ],
      [
        "hunter",
        576,
        393
      ]
    ],
    "walls": [
      [
        637,
        270,
        42,
        419
      ],
      [
        564,
        562,
        42,
        340
      ]
    ],
    "items": []
  },
  {
    "id": "d042",
    "name": "每日 42",
    "code": "42 / DAILY",
    "difficulty": 1.3,
    "difficultyTier": 5,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      206,
      1079
    ],
    "portal": [
      555,
      178
    ],
    "chips": [
      [
        355,
        918
      ],
      [
        652,
        736
      ],
      [
        649,
        379
      ]
    ],
    "enemies": [
      [
        "hunter",
        542,
        897
      ],
      [
        "hunter",
        602,
        214
      ],
      [
        "hunter",
        625,
        563
      ]
    ],
    "walls": [
      [
        72,
        695,
        287,
        42
      ],
      [
        180,
        502,
        282,
        42
      ],
      [
        511,
        336,
        42,
        225
      ]
    ],
    "items": []
  },
  {
    "id": "d043",
    "name": "每日 43",
    "code": "43 / DAILY",
    "difficulty": 3,
    "difficultyTier": 12,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      385,
      1142
    ],
    "portal": [
      535,
      178
    ],
    "chips": [
      [
        540,
        828
      ]
    ],
    "enemies": [
      [
        "hunter",
        416,
        474
      ],
      [
        "hunter",
        557,
        618
      ],
      [
        "hunter",
        399,
        938
      ],
      [
        "hunter",
        437,
        242
      ]
    ],
    "walls": [
      [
        609,
        690,
        42,
        224
      ]
    ],
    "items": []
  },
  {
    "id": "d044",
    "name": "每日 44",
    "code": "44 / DAILY",
    "difficulty": 1.5,
    "difficultyTier": 6,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      206,
      1122
    ],
    "portal": [
      202,
      178
    ],
    "chips": [
      [
        532,
        267
      ],
      [
        572,
        449
      ]
    ],
    "enemies": [
      [
        "hunter",
        436,
        863
      ],
      [
        "hunter",
        278,
        942
      ],
      [
        "hunter",
        133,
        294
      ],
      [
        "hunter",
        557,
        658
      ],
      [
        "hunter",
        348,
        188
      ]
    ],
    "walls": [
      [
        64,
        343,
        286,
        42
      ],
      [
        420,
        372,
        42,
        266
      ]
    ],
    "items": []
  },
  {
    "id": "d045",
    "name": "每日 45",
    "code": "45 / DAILY",
    "difficulty": 3.3,
    "difficultyTier": 13,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      629,
      1114
    ],
    "portal": [
      342,
      178
    ],
    "chips": [
      [
        321,
        232
      ],
      [
        652,
        484
      ],
      [
        529,
        276
      ]
    ],
    "enemies": [
      [
        "hunter",
        631,
        903
      ],
      [
        "hunter",
        654,
        731
      ]
    ],
    "walls": [
      [
        263,
        792,
        293,
        42
      ],
      [
        104,
        306,
        272,
        42
      ],
      [
        170,
        799,
        42,
        391
      ]
    ],
    "items": []
  },
  {
    "id": "d046",
    "name": "每日 46",
    "code": "46 / DAILY",
    "difficulty": 1.8,
    "difficultyTier": 7,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      176,
      1144
    ],
    "portal": [
      246,
      245
    ],
    "chips": [
      [
        277,
        576
      ]
    ],
    "enemies": [
      [
        "hunter",
        295,
        761
      ],
      [
        "hunter",
        334,
        955
      ],
      [
        "hunter",
        273,
        405
      ]
    ],
    "walls": [
      [
        205,
        771,
        42,
        186
      ]
    ],
    "items": []
  },
  {
    "id": "d047",
    "name": "每日 47",
    "code": "47 / DAILY",
    "difficulty": 3.5,
    "difficultyTier": 14,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      476,
      1141
    ],
    "portal": [
      186,
      216
    ],
    "chips": [
      [
        542,
        942
      ],
      [
        332,
        376
      ]
    ],
    "enemies": [
      [
        "hunter",
        135,
        382
      ],
      [
        "hunter",
        611,
        602
      ],
      [
        "hunter",
        585,
        774
      ],
      [
        "hunter",
        484,
        471
      ]
    ],
    "walls": [
      [
        205,
        278,
        214,
        42
      ],
      [
        374,
        978,
        42,
        386
      ]
    ],
    "items": []
  },
  {
    "id": "d048",
    "name": "每日 48",
    "code": "48 / DAILY",
    "difficulty": 2,
    "difficultyTier": 8,
    "tutorial": false,
    "brief": "",
    "parMoves": 9,
    "start": [
      408,
      1090
    ],
    "portal": [
      209,
      649
    ],
    "chips": [
      [
        347,
        286
      ],
      [
        524,
        349
      ],
      [
        160,
        814
      ]
    ],
    "enemies": [
      [
        "hunter",
        154,
        409
      ],
      [
        "hunter",
        608,
        564
      ],
      [
        "hunter",
        517,
        912
      ],
      [
        "hunter",
        119,
        637
      ],
      [
        "hunter",
        530,
        730
      ]
    ],
    "walls": [
      [
        204,
        1018,
        42,
        405
      ],
      [
        310,
        876,
        42,
        298
      ],
      [
        391,
        427,
        42,
        189
      ]
    ],
    "items": []
  },
  {
    "id": "d049",
    "name": "每日 49",
    "code": "49 / DAILY",
    "difficulty": 3.8,
    "difficultyTier": 15,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      558,
      1066
    ],
    "portal": [
      455,
      420
    ],
    "chips": [
      [
        437,
        894
      ]
    ],
    "enemies": [
      [
        "hunter",
        487,
        718
      ],
      [
        "hunter",
        382,
        581
      ]
    ],
    "walls": [
      [
        239,
        286,
        353,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d050",
    "name": "每日 50",
    "code": "50 / DAILY",
    "difficulty": 2.3,
    "difficultyTier": 9,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      372,
      1144
    ],
    "portal": [
      177,
      178
    ],
    "chips": [
      [
        492,
        600
      ],
      [
        489,
        1006
      ]
    ],
    "enemies": [
      [
        "hunter",
        453,
        780
      ],
      [
        "hunter",
        449,
        363
      ],
      [
        "hunter",
        279,
        276
      ]
    ],
    "walls": [
      [
        92,
        846,
        183,
        42
      ],
      [
        560,
        920,
        42,
        333
      ]
    ],
    "items": []
  },
  {
    "id": "d051",
    "name": "每日 51",
    "code": "51 / DAILY",
    "difficulty": 4,
    "difficultyTier": 16,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      467,
      1127
    ],
    "portal": [
      72,
      178
    ],
    "chips": [
      [
        88,
        245
      ],
      [
        277,
        238
      ],
      [
        480,
        235
      ]
    ],
    "enemies": [
      [
        "hunter",
        556,
        735
      ],
      [
        "hunter",
        642,
        354
      ],
      [
        "hunter",
        593,
        969
      ],
      [
        "hunter",
        649,
        566
      ]
    ],
    "walls": [
      [
        83,
        827,
        197,
        42
      ],
      [
        119,
        302,
        337,
        42
      ],
      [
        300,
        1068,
        42,
        407
      ]
    ],
    "items": []
  },
  {
    "id": "d052",
    "name": "每日 52",
    "code": "52 / DAILY",
    "difficulty": 2.5,
    "difficultyTier": 10,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      581,
      1098
    ],
    "portal": [
      70,
      766
    ],
    "chips": [
      [
        78,
        953
      ]
    ],
    "enemies": [
      [
        "hunter",
        408,
        599
      ],
      [
        "hunter",
        559,
        743
      ],
      [
        "hunter",
        77,
        776
      ],
      [
        "hunter",
        563,
        913
      ],
      [
        "hunter",
        178,
        638
      ]
    ],
    "walls": [
      [
        195,
        451,
        418,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d053",
    "name": "每日 53",
    "code": "53 / DAILY",
    "difficulty": 1,
    "difficultyTier": 4,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      369,
      1107
    ],
    "portal": [
      402,
      272
    ],
    "chips": [
      [
        178,
        575
      ],
      [
        382,
        483
      ]
    ],
    "enemies": [
      [
        "hunter",
        100,
        786
      ],
      [
        "hunter",
        178,
        952
      ]
    ],
    "walls": [
      [
        317,
        711,
        42,
        210
      ],
      [
        49,
        433,
        226,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d054",
    "name": "每日 54",
    "code": "54 / DAILY",
    "difficulty": 2.8,
    "difficultyTier": 11,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      584,
      1083
    ],
    "portal": [
      280,
      178
    ],
    "chips": [
      [
        539,
        307
      ],
      [
        364,
        244
      ],
      [
        600,
        735
      ]
    ],
    "enemies": [
      [
        "hunter",
        194,
        274
      ],
      [
        "hunter",
        508,
        926
      ],
      [
        "hunter",
        614,
        506
      ]
    ],
    "walls": [
      [
        436,
        1030,
        42,
        406
      ],
      [
        141,
        325,
        42,
        178
      ],
      [
        47,
        694,
        195,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d055",
    "name": "每日 55",
    "code": "55 / DAILY",
    "difficulty": 1.3,
    "difficultyTier": 5,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      375,
      1131
    ],
    "portal": [
      382,
      186
    ],
    "chips": [
      [
        178,
        479
      ]
    ],
    "enemies": [
      [
        "hunter",
        219,
        1001
      ],
      [
        "hunter",
        361,
        347
      ],
      [
        "hunter",
        71,
        694
      ],
      [
        "hunter",
        74,
        894
      ]
    ],
    "walls": [
      [
        348,
        1012,
        273,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d056",
    "name": "每日 56",
    "code": "56 / DAILY",
    "difficulty": 3,
    "difficultyTier": 12,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      148,
      1133
    ],
    "portal": [
      532,
      254
    ],
    "chips": [
      [
        120,
        791
      ],
      [
        65,
        974
      ]
    ],
    "enemies": [
      [
        "hunter",
        517,
        278
      ],
      [
        "hunter",
        142,
        584
      ],
      [
        "hunter",
        648,
        425
      ],
      [
        "hunter",
        157,
        340
      ],
      [
        "hunter",
        323,
        222
      ]
    ],
    "walls": [
      [
        225,
        734,
        42,
        190
      ],
      [
        242,
        580,
        313,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d057",
    "name": "每日 57",
    "code": "57 / DAILY",
    "difficulty": 1.5,
    "difficultyTier": 6,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      189,
      1099
    ],
    "portal": [
      634,
      178
    ],
    "chips": [
      [
        597,
        262
      ],
      [
        618,
        480
      ],
      [
        328,
        785
      ]
    ],
    "enemies": [
      [
        "hunter",
        546,
        695
      ],
      [
        "hunter",
        187,
        893
      ]
    ],
    "walls": [
      [
        152,
        447,
        402,
        42
      ],
      [
        434,
        1050,
        176,
        42
      ],
      [
        67,
        747,
        42,
        218
      ]
    ],
    "items": []
  },
  {
    "id": "d058",
    "name": "每日 58",
    "code": "58 / DAILY",
    "difficulty": 3.3,
    "difficultyTier": 13,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      144,
      1100
    ],
    "portal": [
      106,
      178
    ],
    "chips": [
      [
        185,
        893
      ]
    ],
    "enemies": [
      [
        "hunter",
        165,
        322
      ],
      [
        "hunter",
        102,
        524
      ],
      [
        "hunter",
        66,
        701
      ]
    ],
    "walls": [
      [
        267,
        605,
        42,
        388
      ]
    ],
    "items": []
  },
  {
    "id": "d059",
    "name": "每日 59",
    "code": "59 / DAILY",
    "difficulty": 1.8,
    "difficultyTier": 7,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      529,
      1141
    ],
    "portal": [
      405,
      178
    ],
    "chips": [
      [
        171,
        306
      ],
      [
        69,
        723
      ]
    ],
    "enemies": [
      [
        "hunter",
        78,
        481
      ],
      [
        "hunter",
        403,
        265
      ],
      [
        "hunter",
        382,
        948
      ],
      [
        "hunter",
        185,
        907
      ]
    ],
    "walls": [
      [
        171,
        1019,
        197,
        42
      ],
      [
        163,
        457,
        324,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d060",
    "name": "每日 60",
    "code": "60 / DAILY",
    "difficulty": 3.5,
    "difficultyTier": 14,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      596,
      1140
    ],
    "portal": [
      627,
      178
    ],
    "chips": [
      [
        378,
        833
      ],
      [
        542,
        225
      ],
      [
        62,
        658
      ]
    ],
    "enemies": [
      [
        "hunter",
        200,
        298
      ],
      [
        "hunter",
        202,
        775
      ],
      [
        "hunter",
        502,
        988
      ],
      [
        "hunter",
        375,
        276
      ],
      [
        "hunter",
        74,
        439
      ]
    ],
    "walls": [
      [
        427,
        362,
        42,
        207
      ],
      [
        314,
        694,
        285,
        42
      ],
      [
        248,
        904,
        42,
        222
      ]
    ],
    "items": []
  },
  {
    "id": "d061",
    "name": "每日 61",
    "code": "61 / DAILY",
    "difficulty": 2,
    "difficultyTier": 8,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      82,
      1067
    ],
    "portal": [
      513,
      393
    ],
    "chips": [
      [
        318,
        742
      ]
    ],
    "enemies": [
      [
        "hunter",
        211,
        941
      ],
      [
        "hunter",
        411,
        569
      ]
    ],
    "walls": [
      [
        594,
        376,
        42,
        229
      ]
    ],
    "items": []
  },
  {
    "id": "d062",
    "name": "每日 62",
    "code": "62 / DAILY",
    "difficulty": 3.8,
    "difficultyTier": 15,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      636,
      1116
    ],
    "portal": [
      192,
      178
    ],
    "chips": [
      [
        131,
        478
      ],
      [
        99,
        305
      ]
    ],
    "enemies": [
      [
        "hunter",
        348,
        584
      ],
      [
        "hunter",
        570,
        648
      ],
      [
        "hunter",
        654,
        880
      ]
    ],
    "walls": [
      [
        153,
        686,
        316,
        42
      ],
      [
        150,
        338,
        336,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d063",
    "name": "每日 63",
    "code": "63 / DAILY",
    "difficulty": 2.3,
    "difficultyTier": 9,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      281,
      1086
    ],
    "portal": [
      112,
      178
    ],
    "chips": [
      [
        155,
        206
      ],
      [
        551,
        228
      ],
      [
        643,
        634
      ]
    ],
    "enemies": [
      [
        "hunter",
        658,
        389
      ],
      [
        "hunter",
        596,
        820
      ],
      [
        "hunter",
        337,
        188
      ],
      [
        "hunter",
        391,
        936
      ]
    ],
    "walls": [
      [
        263,
        814,
        183,
        42
      ],
      [
        144,
        901,
        42,
        413
      ],
      [
        219,
        264,
        181,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d064",
    "name": "每日 64",
    "code": "64 / DAILY",
    "difficulty": 4,
    "difficultyTier": 16,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      363,
      1074
    ],
    "portal": [
      510,
      178
    ],
    "chips": [
      [
        147,
        776
      ]
    ],
    "enemies": [
      [
        "hunter",
        522,
        215
      ],
      [
        "hunter",
        207,
        341
      ],
      [
        "hunter",
        326,
        217
      ],
      [
        "hunter",
        178,
        542
      ],
      [
        "hunter",
        247,
        931
      ]
    ],
    "walls": [
      [
        41,
        545,
        42,
        227
      ]
    ],
    "items": []
  },
  {
    "id": "d065",
    "name": "每日 65",
    "code": "65 / DAILY",
    "difficulty": 2.5,
    "difficultyTier": 10,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      226,
      1127
    ],
    "portal": [
      566,
      329
    ],
    "chips": [
      [
        639,
        665
      ],
      [
        566,
        898
      ]
    ],
    "enemies": [
      [
        "hunter",
        616,
        497
      ],
      [
        "hunter",
        339,
        988
      ]
    ],
    "walls": [
      [
        497,
        491,
        42,
        256
      ],
      [
        90,
        782,
        206,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d066",
    "name": "每日 66",
    "code": "66 / DAILY",
    "difficulty": 1,
    "difficultyTier": 4,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      549,
      1063
    ],
    "portal": [
      394,
      178
    ],
    "chips": [
      [
        387,
        909
      ],
      [
        215,
        195
      ],
      [
        112,
        346
      ]
    ],
    "enemies": [
      [
        "hunter",
        430,
        189
      ],
      [
        "hunter",
        183,
        541
      ],
      [
        "hunter",
        310,
        734
      ]
    ],
    "walls": [
      [
        484,
        396,
        186,
        42
      ],
      [
        244,
        289,
        193,
        42
      ],
      [
        175,
        1080,
        245,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d067",
    "name": "每日 67",
    "code": "67 / DAILY",
    "difficulty": 2.8,
    "difficultyTier": 11,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      531,
      1085
    ],
    "portal": [
      94,
      178
    ],
    "chips": [
      [
        492,
        669
      ]
    ],
    "enemies": [
      [
        "hunter",
        457,
        880
      ],
      [
        "hunter",
        320,
        387
      ],
      [
        "hunter",
        119,
        315
      ],
      [
        "hunter",
        462,
        499
      ]
    ],
    "walls": [
      [
        360,
        513,
        42,
        175
      ]
    ],
    "items": []
  },
  {
    "id": "d068",
    "name": "每日 68",
    "code": "68 / DAILY",
    "difficulty": 1.3,
    "difficultyTier": 5,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      279,
      1131
    ],
    "portal": [
      650,
      285
    ],
    "chips": [
      [
        291,
        897
      ],
      [
        365,
        238
      ]
    ],
    "enemies": [
      [
        "hunter",
        643,
        489
      ],
      [
        "hunter",
        139,
        498
      ],
      [
        "hunter",
        203,
        335
      ],
      [
        "hunter",
        241,
        661
      ],
      [
        "hunter",
        531,
        301
      ]
    ],
    "walls": [
      [
        326,
        583,
        336,
        42
      ],
      [
        154,
        1017,
        42,
        297
      ]
    ],
    "items": []
  },
  {
    "id": "d069",
    "name": "每日 69",
    "code": "69 / DAILY",
    "difficulty": 3,
    "difficultyTier": 12,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      597,
      1076
    ],
    "portal": [
      196,
      178
    ],
    "chips": [
      [
        192,
        357
      ],
      [
        434,
        384
      ],
      [
        588,
        884
      ]
    ],
    "enemies": [
      [
        "hunter",
        624,
        705
      ],
      [
        "hunter",
        609,
        492
      ]
    ],
    "walls": [
      [
        493,
        518,
        42,
        175
      ],
      [
        170,
        550,
        251,
        42
      ],
      [
        354,
        219,
        179,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d070",
    "name": "每日 70",
    "code": "70 / DAILY",
    "difficulty": 1.5,
    "difficultyTier": 6,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      533,
      1066
    ],
    "portal": [
      650,
      178
    ],
    "chips": [
      [
        527,
        409
      ]
    ],
    "enemies": [
      [
        "hunter",
        653,
        237
      ],
      [
        "hunter",
        577,
        842
      ],
      [
        "hunter",
        517,
        651
      ]
    ],
    "walls": [
      [
        361,
        249,
        42,
        387
      ]
    ],
    "items": []
  },
  {
    "id": "d071",
    "name": "每日 71",
    "code": "71 / DAILY",
    "difficulty": 3.3,
    "difficultyTier": 13,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      409,
      1125
    ],
    "portal": [
      411,
      178
    ],
    "chips": [
      [
        188,
        794
      ],
      [
        96,
        618
      ]
    ],
    "enemies": [
      [
        "hunter",
        304,
        253
      ],
      [
        "hunter",
        129,
        413
      ],
      [
        "hunter",
        275,
        1010
      ],
      [
        "hunter",
        518,
        258
      ]
    ],
    "walls": [
      [
        347,
        969,
        250,
        42
      ],
      [
        336,
        522,
        176,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d072",
    "name": "每日 72",
    "code": "72 / DAILY",
    "difficulty": 1.8,
    "difficultyTier": 7,
    "tutorial": false,
    "brief": "",
    "parMoves": 9,
    "start": [
      288,
      1085
    ],
    "portal": [
      168,
      363
    ],
    "chips": [
      [
        449,
        246
      ],
      [
        472,
        769
      ],
      [
        95,
        572
      ]
    ],
    "enemies": [
      [
        "hunter",
        606,
        388
      ],
      [
        "hunter",
        613,
        629
      ],
      [
        "hunter",
        279,
        238
      ],
      [
        "hunter",
        323,
        896
      ],
      [
        "hunter",
        140,
        341
      ]
    ],
    "walls": [
      [
        489,
        1077,
        181,
        42
      ],
      [
        241,
        409,
        42,
        259
      ],
      [
        153,
        536,
        42,
        206
      ]
    ],
    "items": []
  },
  {
    "id": "d073",
    "name": "每日 73",
    "code": "73 / DAILY",
    "difficulty": 3.5,
    "difficultyTier": 14,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      307,
      1087
    ],
    "portal": [
      132,
      247
    ],
    "chips": [
      [
        93,
        413
      ]
    ],
    "enemies": [
      [
        "hunter",
        168,
        637
      ],
      [
        "hunter",
        262,
        850
      ]
    ],
    "walls": [
      [
        378,
        1062,
        42,
        240
      ]
    ],
    "items": []
  },
  {
    "id": "d074",
    "name": "每日 74",
    "code": "74 / DAILY",
    "difficulty": 2,
    "difficultyTier": 8,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      269,
      1106
    ],
    "portal": [
      559,
      178
    ],
    "chips": [
      [
        306,
        667
      ],
      [
        298,
        861
      ]
    ],
    "enemies": [
      [
        "hunter",
        280,
        437
      ],
      [
        "hunter",
        373,
        239
      ],
      [
        "hunter",
        545,
        193
      ]
    ],
    "walls": [
      [
        427,
        954,
        42,
        223
      ],
      [
        420,
        264,
        42,
        179
      ]
    ],
    "items": []
  },
  {
    "id": "d075",
    "name": "每日 75",
    "code": "75 / DAILY",
    "difficulty": 3.8,
    "difficultyTier": 15,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      156,
      1102
    ],
    "portal": [
      532,
      178
    ],
    "chips": [
      [
        70,
        329
      ],
      [
        191,
        197
      ],
      [
        592,
        279
      ]
    ],
    "enemies": [
      [
        "hunter",
        165,
        914
      ],
      [
        "hunter",
        91,
        753
      ],
      [
        "hunter",
        429,
        215
      ],
      [
        "hunter",
        82,
        572
      ]
    ],
    "walls": [
      [
        537,
        778,
        42,
        372
      ],
      [
        226,
        522,
        323,
        42
      ],
      [
        263,
        772,
        42,
        196
      ]
    ],
    "items": []
  },
  {
    "id": "d076",
    "name": "每日 76",
    "code": "76 / DAILY",
    "difficulty": 2.3,
    "difficultyTier": 9,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      449,
      1082
    ],
    "portal": [
      123,
      178
    ],
    "chips": [
      [
        601,
        711
      ]
    ],
    "enemies": [
      [
        "hunter",
        409,
        202
      ],
      [
        "hunter",
        634,
        528
      ],
      [
        "hunter",
        516,
        905
      ],
      [
        "hunter",
        235,
        217
      ],
      [
        "hunter",
        568,
        326
      ]
    ],
    "walls": [
      [
        189,
        306,
        237,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d077",
    "name": "每日 77",
    "code": "77 / DAILY",
    "difficulty": 4,
    "difficultyTier": 16,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      302,
      1092
    ],
    "portal": [
      597,
      178
    ],
    "chips": [
      [
        541,
        352
      ],
      [
        609,
        573
      ]
    ],
    "enemies": [
      [
        "hunter",
        456,
        906
      ],
      [
        "hunter",
        590,
        779
      ]
    ],
    "walls": [
      [
        120,
        687,
        344,
        42
      ],
      [
        210,
        871,
        42,
        256
      ]
    ],
    "items": []
  },
  {
    "id": "d078",
    "name": "每日 78",
    "code": "78 / DAILY",
    "difficulty": 2.5,
    "difficultyTier": 10,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      217,
      1080
    ],
    "portal": [
      559,
      707
    ],
    "chips": [
      [
        290,
        591
      ],
      [
        595,
        705
      ],
      [
        630,
        910
      ]
    ],
    "enemies": [
      [
        "hunter",
        92,
        941
      ],
      [
        "hunter",
        464,
        576
      ],
      [
        "hunter",
        121,
        768
      ]
    ],
    "walls": [
      [
        80,
        455,
        225,
        42
      ],
      [
        30,
        226,
        405,
        42
      ],
      [
        378,
        487,
        249,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d079",
    "name": "每日 79",
    "code": "79 / DAILY",
    "difficulty": 1,
    "difficultyTier": 4,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      196,
      1131
    ],
    "portal": [
      70,
      178
    ],
    "chips": [
      [
        101,
        228
      ]
    ],
    "enemies": [
      [
        "hunter",
        221,
        558
      ],
      [
        "hunter",
        307,
        985
      ],
      [
        "hunter",
        358,
        756
      ],
      [
        "hunter",
        92,
        434
      ]
    ],
    "walls": [
      [
        371,
        901,
        42,
        308
      ]
    ],
    "items": []
  },
  {
    "id": "d080",
    "name": "每日 80",
    "code": "80 / DAILY",
    "difficulty": 2.8,
    "difficultyTier": 11,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      339,
      1093
    ],
    "portal": [
      527,
      178
    ],
    "chips": [
      [
        68,
        611
      ],
      [
        449,
        192
      ]
    ],
    "enemies": [
      [
        "hunter",
        144,
        779
      ],
      [
        "hunter",
        205,
        958
      ],
      [
        "hunter",
        263,
        222
      ],
      [
        "hunter",
        171,
        399
      ],
      [
        "hunter",
        645,
        195
      ]
    ],
    "walls": [
      [
        298,
        286,
        289,
        42
      ],
      [
        387,
        796,
        283,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d081",
    "name": "每日 81",
    "code": "81 / DAILY",
    "difficulty": 1.3,
    "difficultyTier": 5,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      272,
      1138
    ],
    "portal": [
      547,
      178
    ],
    "chips": [
      [
        78,
        762
      ],
      [
        149,
        973
      ],
      [
        191,
        602
      ]
    ],
    "enemies": [
      [
        "hunter",
        432,
        261
      ],
      [
        "hunter",
        327,
        402
      ]
    ],
    "walls": [
      [
        248,
        983,
        334,
        42
      ],
      [
        419,
        376,
        42,
        177
      ],
      [
        328,
        780,
        345,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d082",
    "name": "每日 82",
    "code": "82 / DAILY",
    "difficulty": 3,
    "difficultyTier": 12,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      629,
      1078
    ],
    "portal": [
      506,
      178
    ],
    "chips": [
      [
        635,
        860
      ]
    ],
    "enemies": [
      [
        "hunter",
        497,
        701
      ],
      [
        "hunter",
        534,
        484
      ],
      [
        "hunter",
        559,
        282
      ]
    ],
    "walls": [
      [
        387,
        280,
        42,
        367
      ]
    ],
    "items": []
  },
  {
    "id": "d083",
    "name": "每日 83",
    "code": "83 / DAILY",
    "difficulty": 1.5,
    "difficultyTier": 6,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      366,
      1091
    ],
    "portal": [
      384,
      178
    ],
    "chips": [
      [
        206,
        940
      ],
      [
        128,
        525
      ]
    ],
    "enemies": [
      [
        "hunter",
        126,
        724
      ],
      [
        "hunter",
        171,
        329
      ],
      [
        "hunter",
        492,
        217
      ],
      [
        "hunter",
        304,
        190
      ]
    ],
    "walls": [
      [
        227,
        533,
        333,
        42
      ],
      [
        349,
        942,
        175,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d084",
    "name": "每日 84",
    "code": "84 / DAILY",
    "difficulty": 3.3,
    "difficultyTier": 13,
    "tutorial": false,
    "brief": "",
    "parMoves": 9,
    "start": [
      566,
      1146
    ],
    "portal": [
      439,
      178
    ],
    "chips": [
      [
        418,
        1019
      ],
      [
        216,
        353
      ],
      [
        365,
        201
      ]
    ],
    "enemies": [
      [
        "hunter",
        190,
        526
      ],
      [
        "hunter",
        241,
        1008
      ],
      [
        "hunter",
        558,
        221
      ],
      [
        "hunter",
        105,
        674
      ],
      [
        "hunter",
        123,
        849
      ]
    ],
    "walls": [
      [
        538,
        268,
        42,
        243
      ],
      [
        84,
        1060,
        235,
        42
      ],
      [
        300,
        570,
        42,
        330
      ]
    ],
    "items": []
  },
  {
    "id": "d085",
    "name": "每日 85",
    "code": "85 / DAILY",
    "difficulty": 1.8,
    "difficultyTier": 7,
    "tutorial": false,
    "brief": "",
    "parMoves": 4,
    "start": [
      570,
      1108
    ],
    "portal": [
      533,
      390
    ],
    "chips": [
      [
        489,
        585
      ]
    ],
    "enemies": [
      [
        "hunter",
        636,
        941
      ],
      [
        "hunter",
        600,
        714
      ]
    ],
    "walls": [
      [
        333,
        395,
        42,
        276
      ]
    ],
    "items": []
  },
  {
    "id": "d086",
    "name": "每日 86",
    "code": "86 / DAILY",
    "difficulty": 3.5,
    "difficultyTier": 14,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      549,
      1077
    ],
    "portal": [
      283,
      178
    ],
    "chips": [
      [
        612,
        468
      ],
      [
        239,
        307
      ]
    ],
    "enemies": [
      [
        "hunter",
        603,
        668
      ],
      [
        "hunter",
        516,
        845
      ],
      [
        "hunter",
        466,
        292
      ]
    ],
    "walls": [
      [
        194,
        684,
        318,
        42
      ],
      [
        48,
        405,
        411,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d087",
    "name": "每日 87",
    "code": "87 / DAILY",
    "difficulty": 2,
    "difficultyTier": 8,
    "tutorial": false,
    "brief": "",
    "parMoves": 8,
    "start": [
      226,
      1092
    ],
    "portal": [
      70,
      200
    ],
    "chips": [
      [
        66,
        376
      ],
      [
        177,
        231
      ],
      [
        473,
        736
      ]
    ],
    "enemies": [
      [
        "hunter",
        572,
        584
      ],
      [
        "hunter",
        350,
        218
      ],
      [
        "hunter",
        398,
        964
      ],
      [
        "hunter",
        512,
        368
      ]
    ],
    "walls": [
      [
        86,
        985,
        42,
        367
      ],
      [
        64,
        707,
        265,
        42
      ],
      [
        619,
        670,
        42,
        184
      ]
    ],
    "items": []
  },
  {
    "id": "d088",
    "name": "每日 88",
    "code": "88 / DAILY",
    "difficulty": 3.8,
    "difficultyTier": 15,
    "tutorial": false,
    "brief": "",
    "parMoves": 7,
    "start": [
      611,
      1149
    ],
    "portal": [
      70,
      204
    ],
    "chips": [
      [
        645,
        957
      ]
    ],
    "enemies": [
      [
        "hunter",
        84,
        411
      ],
      [
        "hunter",
        77,
        607
      ],
      [
        "hunter",
        431,
        684
      ],
      [
        "hunter",
        206,
        719
      ],
      [
        "hunter",
        559,
        806
      ]
    ],
    "walls": [
      [
        97,
        787,
        326,
        42
      ]
    ],
    "items": []
  },
  {
    "id": "d089",
    "name": "每日 89",
    "code": "89 / DAILY",
    "difficulty": 2.3,
    "difficultyTier": 9,
    "tutorial": false,
    "brief": "",
    "parMoves": 5,
    "start": [
      570,
      1110
    ],
    "portal": [
      390,
      199
    ],
    "chips": [
      [
        611,
        738
      ],
      [
        482,
        387
      ]
    ],
    "enemies": [
      [
        "hunter",
        517,
        568
      ],
      [
        "hunter",
        631,
        912
      ]
    ],
    "walls": [
      [
        154,
        332,
        42,
        363
      ],
      [
        502,
        707,
        42,
        178
      ]
    ],
    "items": []
  },
  {
    "id": "d090",
    "name": "每日 90",
    "code": "90 / DAILY",
    "difficulty": 4,
    "difficultyTier": 16,
    "tutorial": false,
    "brief": "",
    "parMoves": 6,
    "start": [
      311,
      1090
    ],
    "portal": [
      489,
      178
    ],
    "chips": [
      [
        185,
        905
      ],
      [
        277,
        207
      ],
      [
        92,
        731
      ]
    ],
    "enemies": [
      [
        "hunter",
        112,
        552
      ],
      [
        "hunter",
        127,
        315
      ],
      [
        "hunter",
        466,
        242
      ]
    ],
    "walls": [
      [
        381,
        939,
        42,
        385
      ],
      [
        419,
        352,
        42,
        400
      ],
      [
        321,
        612,
        42,
        243
      ]
    ],
    "items": []
  }
];

export const DAILY_ROUTES = [
  [
    [
      122.98,
      935.99
    ],
    [
      157.12,
      725.69
    ],
    [
      80.47,
      532.27
    ],
    [
      195.15,
      335.35
    ]
  ],
  [
    [
      302.67,
      937.28
    ],
    [
      393.57,
      725.87
    ],
    [
      577.17,
      644.11
    ],
    [
      657.78,
      437.74
    ],
    [
      550.81,
      272.01
    ],
    [
      528.82,
      178
    ]
  ],
  [
    [
      608.03,
      894.87
    ],
    [
      609.38,
      701.52
    ],
    [
      652.67,
      490.25
    ],
    [
      565.63,
      267.19
    ],
    [
      344.45,
      202.46
    ],
    [
      158.76,
      282.28
    ],
    [
      64.4,
      472.36
    ],
    [
      138.26,
      310.39
    ]
  ],
  [
    [
      312.66,
      849.7
    ],
    [
      538.28,
      765.09
    ],
    [
      643.46,
      573.81
    ],
    [
      578.57,
      347.66
    ],
    [
      462.76,
      205.85
    ],
    [
      235.35,
      214.14
    ],
    [
      239.56,
      178
    ]
  ],
  [
    [
      363.38,
      918.35
    ],
    [
      392.71,
      734.8
    ],
    [
      523.38,
      623.74
    ],
    [
      645.13,
      470.3
    ],
    [
      650,
      255.94
    ]
  ],
  [
    [
      314.06,
      919.15
    ],
    [
      186.58,
      753.63
    ],
    [
      101.82,
      559.77
    ],
    [
      187.29,
      342.65
    ],
    [
      324.55,
      229.42
    ],
    [
      519.54,
      279
    ],
    [
      458.59,
      178
    ]
  ],
  [
    [
      574.92,
      915.44
    ],
    [
      528.82,
      734.22
    ],
    [
      501.45,
      506.72
    ],
    [
      392.05,
      334.11
    ],
    [
      181.21,
      278.34
    ],
    [
      213.14,
      178
    ]
  ],
  [
    [
      467,
      914
    ],
    [
      170,
      575
    ],
    [
      64,
      556
    ],
    [
      66.67,
      287.84
    ],
    [
      449,
      178
    ],
    [
      449,
      178
    ]
  ],
  [
    [
      407.44,
      967.12
    ],
    [
      491.78,
      749.89
    ],
    [
      489.18,
      541.69
    ],
    [
      649.22,
      393.19
    ],
    [
      654.49,
      198.95
    ],
    [
      650,
      178
    ]
  ],
  [
    [
      341.04,
      896.38
    ],
    [
      138.23,
      793.96
    ],
    [
      93.23,
      603.69
    ],
    [
      189.77,
      394.5
    ],
    [
      137.52,
      181.87
    ]
  ],
  [
    [
      303.77,
      867.78
    ],
    [
      319.24,
      649.36
    ],
    [
      174.21,
      513.13
    ],
    [
      156.5,
      313.45
    ],
    [
      297.02,
      188.68
    ],
    [
      499.17,
      189.8
    ],
    [
      394.45,
      178
    ]
  ],
  [
    [
      495.86,
      939.11
    ],
    [
      616.89,
      746.46
    ],
    [
      624.14,
      542.71
    ],
    [
      547.6,
      341.59
    ],
    [
      392.71,
      215.92
    ],
    [
      207.58,
      222.06
    ],
    [
      64.56,
      416.05
    ],
    [
      126.79,
      640.18
    ],
    [
      156.11,
      465.79
    ]
  ],
  [
    [
      577.18,
      846.21
    ],
    [
      483.22,
      633.65
    ],
    [
      258.88,
      579.78
    ],
    [
      310.1,
      417
    ]
  ],
  [
    [
      485.14,
      845.77
    ],
    [
      531.02,
      662.84
    ],
    [
      515.61,
      479.55
    ],
    [
      390.78,
      281.06
    ],
    [
      191.01,
      242.97
    ],
    [
      198.31,
      178
    ]
  ],
  [
    [
      325.76,
      943.02
    ],
    [
      518.39,
      881.74
    ],
    [
      651.26,
      705.44
    ],
    [
      588.42,
      465.62
    ],
    [
      555.87,
      280.94
    ],
    [
      404.72,
      198.85
    ],
    [
      170.77,
      216.49
    ],
    [
      178.04,
      178
    ]
  ],
  [
    [
      567.22,
      887.57
    ],
    [
      604.48,
      683.7
    ],
    [
      509.35,
      509.51
    ],
    [
      487.84,
      326.27
    ],
    [
      305.69,
      210.87
    ],
    [
      83.11,
      243.34
    ],
    [
      70,
      178
    ]
  ],
  [
    [
      84.44,
      903.01
    ],
    [
      178.66,
      733.74
    ],
    [
      323.03,
      579.47
    ],
    [
      513.08,
      511.55
    ],
    [
      426.05,
      321.23
    ]
  ],
  [
    [
      318.52,
      856.09
    ],
    [
      124.23,
      717.42
    ],
    [
      78.1,
      540.27
    ],
    [
      149.39,
      375.08
    ],
    [
      240.19,
      225.04
    ],
    [
      418.92,
      201.06
    ],
    [
      532.15,
      178
    ]
  ],
  [
    [
      276.58,
      933.55
    ],
    [
      304.87,
      725.29
    ],
    [
      359.02,
      536.63
    ],
    [
      281.71,
      302.54
    ],
    [
      112.1,
      196.64
    ],
    [
      70,
      178
    ]
  ],
  [
    [
      613.19,
      851.11
    ],
    [
      526.11,
      664.24
    ],
    [
      598,
      490.57
    ],
    [
      474.25,
      284.36
    ],
    [
      316.72,
      209.77
    ],
    [
      156.92,
      270.63
    ],
    [
      79.79,
      471.22
    ],
    [
      70,
      283.26
    ]
  ],
  [
    [
      495.11,
      961.58
    ],
    [
      352.49,
      829.52
    ],
    [
      238.01,
      697.6
    ],
    [
      122.78,
      550.61
    ],
    [
      156.98,
      313.38
    ],
    [
      70,
      178
    ]
  ],
  [
    [
      280.55,
      941.86
    ],
    [
      171.27,
      746.09
    ],
    [
      184.7,
      510.67
    ],
    [
      116.68,
      349.12
    ],
    [
      112.75,
      178
    ]
  ],
  [
    [
      234.14,
      890.33
    ],
    [
      182.07,
      711.93
    ],
    [
      91,
      538.41
    ],
    [
      133.72,
      338.04
    ],
    [
      241.47,
      205.04
    ],
    [
      465.04,
      192.33
    ],
    [
      525.07,
      178
    ]
  ],
  [
    [
      133,
      684
    ],
    [
      155.01,
      931.45
    ],
    [
      182,
      369
    ],
    [
      132.87,
      360.27
    ],
    [
      327.66,
      202.65
    ],
    [
      597.66,
      202.65
    ]
  ],
  [
    [
      591.3,
      929.71
    ],
    [
      652.09,
      690
    ],
    [
      566.93,
      485.25
    ],
    [
      460.9,
      335.24
    ]
  ],
  [
    [
      595.92,
      993.06
    ],
    [
      589.37,
      804.84
    ],
    [
      418.91,
      672.06
    ],
    [
      349.24,
      457.49
    ],
    [
      420.11,
      284.31
    ],
    [
      396.17,
      178
    ]
  ],
  [
    [
      315.54,
      946.06
    ],
    [
      519.89,
      890.75
    ],
    [
      632.8,
      735.18
    ],
    [
      637,
      490.24
    ],
    [
      598.23,
      312.22
    ],
    [
      446.94,
      214.65
    ],
    [
      241.88,
      270.1
    ],
    [
      311.17,
      178
    ]
  ],
  [
    [
      431.02,
      1003.26
    ],
    [
      246.01,
      937.18
    ],
    [
      94.86,
      803.88
    ],
    [
      111.1,
      573.2
    ],
    [
      230.84,
      361.33
    ],
    [
      408.99,
      241.75
    ],
    [
      497.36,
      178
    ]
  ],
  [
    [
      371.01,
      918.85
    ],
    [
      215.41,
      780.14
    ],
    [
      185.23,
      561.98
    ],
    [
      213.59,
      351.36
    ],
    [
      269.24,
      198.84
    ]
  ],
  [
    [
      447.74,
      864.38
    ],
    [
      632.22,
      728.59
    ],
    [
      648.41,
      542.93
    ],
    [
      537.36,
      391.7
    ],
    [
      339.05,
      349.58
    ],
    [
      120.56,
      461.63
    ],
    [
      70,
      255.62
    ]
  ],
  [
    [
      531.6,
      869.14
    ],
    [
      627.74,
      667.11
    ],
    [
      627.94,
      444.59
    ],
    [
      498.14,
      312.29
    ],
    [
      292.57,
      211.78
    ],
    [
      173.16,
      178
    ]
  ],
  [
    [
      338.38,
      911.78
    ],
    [
      534.44,
      800.03
    ],
    [
      643.15,
      581.16
    ],
    [
      623.94,
      347.28
    ],
    [
      488.47,
      227.76
    ],
    [
      320,
      190.16
    ],
    [
      80.8,
      193.39
    ],
    [
      167.16,
      178
    ]
  ],
  [
    [
      437.6,
      956.73
    ],
    [
      344.55,
      738.11
    ],
    [
      144.38,
      658.95
    ],
    [
      70.69,
      504.73
    ],
    [
      171.71,
      317.38
    ],
    [
      207.2,
      178
    ]
  ],
  [
    [
      472.77,
      890.55
    ],
    [
      567.82,
      722.6
    ],
    [
      528.89,
      556.23
    ],
    [
      466.93,
      339.13
    ],
    [
      452.72,
      178
    ]
  ],
  [
    [
      461,
      988.56
    ],
    [
      533.76,
      752.23
    ],
    [
      577.69,
      559.67
    ],
    [
      444.77,
      374.31
    ],
    [
      244.11,
      260.11
    ],
    [
      63.24,
      206.62
    ],
    [
      175.84,
      178
    ]
  ],
  [
    [
      521.32,
      873.55
    ],
    [
      624.64,
      624.1
    ],
    [
      521.32,
      374.65
    ],
    [
      271.87,
      271.33
    ],
    [
      80.95,
      462.25
    ],
    [
      145.9,
      733.87
    ],
    [
      127,
      593
    ]
  ],
  [
    [
      137.78,
      857.49
    ],
    [
      303.36,
      676.59
    ],
    [
      346.26,
      498.42
    ],
    [
      321.18,
      333.04
    ]
  ],
  [
    [
      314.79,
      915.79
    ],
    [
      284.93,
      719.42
    ],
    [
      219.79,
      555.73
    ],
    [
      342.69,
      354.11
    ],
    [
      502.15,
      201.72
    ],
    [
      401.78,
      178
    ]
  ],
  [
    [
      589.26,
      1015.97
    ],
    [
      640.47,
      809.45
    ],
    [
      612.54,
      619.44
    ],
    [
      579.8,
      439.96
    ],
    [
      406.26,
      332.01
    ],
    [
      229.19,
      318.67
    ],
    [
      71.27,
      421.27
    ],
    [
      70,
      229.53
    ]
  ],
  [
    [
      493.79,
      958.47
    ],
    [
      452.15,
      754.98
    ],
    [
      584.84,
      595.42
    ],
    [
      545.23,
      363.92
    ],
    [
      420.37,
      228.88
    ],
    [
      213.03,
      230.9
    ],
    [
      120.79,
      178
    ]
  ],
  [
    [
      377.35,
      955.83
    ],
    [
      365.06,
      750.28
    ],
    [
      494.06,
      570.1
    ],
    [
      576.29,
      393.15
    ],
    [
      504.86,
      220.87
    ]
  ],
  [
    [
      354.94,
      918.49
    ],
    [
      541.57,
      896.96
    ],
    [
      651.6,
      735.55
    ],
    [
      624.59,
      563.41
    ],
    [
      649.01,
      379.02
    ],
    [
      602.14,
      213.94
    ],
    [
      554.74,
      178
    ]
  ],
  [
    [
      398.86,
      938.49
    ],
    [
      539.76,
      827.59
    ],
    [
      556.9,
      617.68
    ],
    [
      416.07,
      474
    ],
    [
      437.05,
      241.88
    ],
    [
      534.93,
      178
    ]
  ],
  [
    [
      277.95,
      941.54
    ],
    [
      436.43,
      863.1
    ],
    [
      556.54,
      658.1
    ],
    [
      572.33,
      448.67
    ],
    [
      532.48,
      267.21
    ],
    [
      347.96,
      188.05
    ],
    [
      132.79,
      294.24
    ],
    [
      201.75,
      178
    ]
  ],
  [
    [
      631.47,
      902.98
    ],
    [
      654.3,
      730.74
    ],
    [
      652.5,
      483.89
    ],
    [
      529.36,
      276.22
    ],
    [
      321.16,
      231.68
    ],
    [
      342.44,
      178
    ]
  ],
  [
    [
      334.14,
      954.83
    ],
    [
      295.15,
      761.47
    ],
    [
      277.35,
      575.62
    ],
    [
      272.77,
      405.4
    ],
    [
      245.68,
      245.25
    ]
  ],
  [
    [
      542.25,
      942.3
    ],
    [
      585.07,
      773.59
    ],
    [
      610.86,
      601.68
    ],
    [
      484.37,
      471.01
    ],
    [
      332.08,
      375.83
    ],
    [
      135.24,
      382.03
    ],
    [
      185.61,
      216.3
    ]
  ],
  [
    [
      516.62,
      912.21
    ],
    [
      530.08,
      729.66
    ],
    [
      608.3,
      564.19
    ],
    [
      524.23,
      348.87
    ],
    [
      346.96,
      285.95
    ],
    [
      154.49,
      409.49
    ],
    [
      118.77,
      636.98
    ],
    [
      160.46,
      813.72
    ],
    [
      209.02,
      648.9
    ]
  ],
  [
    [
      436.83,
      893.76
    ],
    [
      486.98,
      717.73
    ],
    [
      382.07,
      581.47
    ],
    [
      454.98,
      420.3
    ]
  ],
  [
    [
      488.61,
      1005.94
    ],
    [
      452.81,
      779.97
    ],
    [
      491.85,
      599.71
    ],
    [
      448.69,
      362.65
    ],
    [
      278.6,
      276.01
    ],
    [
      177.11,
      178
    ]
  ],
  [
    [
      592.82,
      969.08
    ],
    [
      555.92,
      734.89
    ],
    [
      649.45,
      565.75
    ],
    [
      642.05,
      354.4
    ],
    [
      479.59,
      234.65
    ],
    [
      276.82,
      237.62
    ],
    [
      88.4,
      245.17
    ],
    [
      71.62,
      178
    ]
  ],
  [
    [
      563.06,
      912.91
    ],
    [
      558.66,
      742.79
    ],
    [
      408.5,
      599.03
    ],
    [
      178.07,
      637.91
    ],
    [
      76.89,
      776.27
    ],
    [
      78.49,
      953.14
    ],
    [
      70,
      765.84
    ]
  ],
  [
    [
      177.66,
      951.58
    ],
    [
      99.69,
      785.93
    ],
    [
      178.23,
      575.45
    ],
    [
      382.11,
      483.21
    ],
    [
      402.49,
      271.95
    ]
  ],
  [
    [
      508.29,
      925.88
    ],
    [
      599.91,
      734.68
    ],
    [
      613.54,
      506.39
    ],
    [
      538.6,
      306.68
    ],
    [
      363.95,
      243.85
    ],
    [
      193.5,
      273.57
    ],
    [
      280.14,
      178
    ]
  ],
  [
    [
      218.54,
      1001.04
    ],
    [
      73.9,
      894.16
    ],
    [
      70.86,
      693.64
    ],
    [
      177.62,
      478.72
    ],
    [
      361.38,
      346.67
    ],
    [
      381.85,
      185.95
    ]
  ],
  [
    [
      44.68,
      883.55
    ],
    [
      319.59,
      233.59
    ],
    [
      154.4,
      360.69
    ],
    [
      154.33,
      138
    ],
    [
      486.87,
      298.87
    ],
    [
      605.79,
      431.54
    ],
    [
      532,
      254
    ]
  ],
  [
    [
      187.48,
      893.3
    ],
    [
      327.67,
      784.56
    ],
    [
      545.98,
      694.97
    ],
    [
      617.92,
      479.57
    ],
    [
      596.9,
      261.78
    ],
    [
      634.2,
      178
    ]
  ],
  [
    [
      184.64,
      892.89
    ],
    [
      66.45,
      701.02
    ],
    [
      102.29,
      524.44
    ],
    [
      164.79,
      321.97
    ],
    [
      106.29,
      178
    ]
  ],
  [
    [
      381.97,
      947.7
    ],
    [
      185.47,
      907.18
    ],
    [
      69.29,
      723.09
    ],
    [
      78.15,
      480.5
    ],
    [
      170.89,
      306.44
    ],
    [
      403.13,
      265.02
    ],
    [
      404.86,
      178
    ]
  ],
  [
    [
      200,
      298
    ],
    [
      209.28,
      780.65
    ],
    [
      41.52,
      599.53
    ],
    [
      144.84,
      350.08
    ],
    [
      542,
      225
    ],
    [
      627,
      178
    ]
  ],
  [
    [
      211.41,
      941.09
    ],
    [
      317.78,
      742.02
    ],
    [
      411.03,
      569.11
    ],
    [
      512.69,
      393.37
    ]
  ],
  [
    [
      653.91,
      880.12
    ],
    [
      569.7,
      648.35
    ],
    [
      348.35,
      583.63
    ],
    [
      131.21,
      477.96
    ],
    [
      99.44,
      305.45
    ],
    [
      192.01,
      178
    ]
  ],
  [
    [
      390.59,
      935.9
    ],
    [
      596.08,
      819.82
    ],
    [
      643.19,
      633.62
    ],
    [
      658.16,
      389.08
    ],
    [
      551.05,
      227.98
    ],
    [
      336.76,
      188.43
    ],
    [
      155.36,
      205.98
    ],
    [
      111.87,
      178
    ]
  ],
  [
    [
      246.93,
      931.29
    ],
    [
      146.58,
      775.97
    ],
    [
      177.8,
      541.89
    ],
    [
      206.9,
      340.52
    ],
    [
      326.12,
      217.35
    ],
    [
      521.95,
      215.49
    ],
    [
      509.54,
      178
    ]
  ],
  [
    [
      338.6,
      987.62
    ],
    [
      565.6,
      898.03
    ],
    [
      638.97,
      665.46
    ],
    [
      616.29,
      496.8
    ],
    [
      566.07,
      329.06
    ]
  ],
  [
    [
      387.09,
      909.4
    ],
    [
      310.21,
      734
    ],
    [
      183.44,
      541.25
    ],
    [
      111.71,
      346.28
    ],
    [
      214.54,
      194.91
    ],
    [
      430.19,
      188.84
    ],
    [
      394,
      178
    ]
  ],
  [
    [
      457.06,
      879.77
    ],
    [
      491.53,
      669.43
    ],
    [
      461.52,
      499.4
    ],
    [
      319.89,
      386.94
    ],
    [
      119.33,
      314.73
    ],
    [
      94.45,
      178
    ]
  ],
  [
    [
      290.58,
      896.74
    ],
    [
      241.43,
      660.96
    ],
    [
      138.61,
      497.71
    ],
    [
      203.11,
      334.71
    ],
    [
      364.81,
      237.7
    ],
    [
      531.05,
      300.65
    ],
    [
      643.15,
      488.68
    ],
    [
      650,
      284.88
    ]
  ],
  [
    [
      587.51,
      884.14
    ],
    [
      623.7,
      705.01
    ],
    [
      608.64,
      492.21
    ],
    [
      434.19,
      384.12
    ],
    [
      191.68,
      357.35
    ],
    [
      195.97,
      178
    ]
  ],
  [
    [
      576.66,
      842.17
    ],
    [
      516.62,
      650.95
    ],
    [
      526.61,
      408.75
    ],
    [
      652.85,
      236.92
    ],
    [
      650,
      178
    ]
  ],
  [
    [
      274.61,
      1010.47
    ],
    [
      187.92,
      794.48
    ],
    [
      96.31,
      617.67
    ],
    [
      129.18,
      413.18
    ],
    [
      304.45,
      252.52
    ],
    [
      517.81,
      258.33
    ],
    [
      410.57,
      178
    ]
  ],
  [
    [
      323.08,
      895.72
    ],
    [
      472.33,
      769.48
    ],
    [
      612.66,
      628.55
    ],
    [
      606.41,
      388.04
    ],
    [
      449.43,
      245.75
    ],
    [
      279.39,
      238.37
    ],
    [
      140.16,
      341.47
    ],
    [
      94.64,
      572.19
    ],
    [
      168.39,
      362.91
    ]
  ],
  [
    [
      262.15,
      850
    ],
    [
      168.2,
      636.84
    ],
    [
      92.99,
      413.27
    ],
    [
      131.74,
      246.88
    ]
  ],
  [
    [
      298.05,
      861.06
    ],
    [
      306.43,
      667.08
    ],
    [
      280.39,
      436.59
    ],
    [
      373.17,
      239.2
    ],
    [
      545.3,
      192.72
    ],
    [
      559.01,
      178
    ]
  ],
  [
    [
      164.82,
      914.4
    ],
    [
      91.37,
      753.36
    ],
    [
      82.28,
      571.62
    ],
    [
      70.29,
      328.83
    ],
    [
      191.44,
      196.51
    ],
    [
      429.41,
      214.97
    ],
    [
      592.49,
      278.82
    ],
    [
      531.59,
      178
    ]
  ],
  [
    [
      515.98,
      905.24
    ],
    [
      601.06,
      710.91
    ],
    [
      633.96,
      528.49
    ],
    [
      568,
      326.32
    ],
    [
      409.47,
      201.92
    ],
    [
      234.55,
      217.15
    ],
    [
      123.04,
      178
    ]
  ],
  [
    [
      456.39,
      905.57
    ],
    [
      589.73,
      778.76
    ],
    [
      609.36,
      573.49
    ],
    [
      541.18,
      352.35
    ],
    [
      596.77,
      178
    ]
  ],
  [
    [
      91.65,
      940.64
    ],
    [
      121.09,
      768.24
    ],
    [
      289.84,
      590.56
    ],
    [
      464.06,
      575.75
    ],
    [
      594.69,
      705.06
    ],
    [
      629.93,
      910.03
    ],
    [
      559.01,
      706.74
    ]
  ],
  [
    [
      306.75,
      984.66
    ],
    [
      357.54,
      756.03
    ],
    [
      221.31,
      557.91
    ],
    [
      91.75,
      433.9
    ],
    [
      101.15,
      227.79
    ],
    [
      70,
      178
    ]
  ],
  [
    [
      205.12,
      958.49
    ],
    [
      144.15,
      778.96
    ],
    [
      67.74,
      611.33
    ],
    [
      171.26,
      398.73
    ],
    [
      262.88,
      221.66
    ],
    [
      448.77,
      192.21
    ],
    [
      644.9,
      195.17
    ],
    [
      526.91,
      178
    ]
  ],
  [
    [
      149.01,
      972.89
    ],
    [
      78.19,
      761.79
    ],
    [
      191.11,
      602.34
    ],
    [
      327.12,
      402.33
    ],
    [
      431.51,
      261.47
    ],
    [
      546.94,
      178
    ]
  ],
  [
    [
      635.11,
      860.44
    ],
    [
      496.88,
      700.7
    ],
    [
      533.55,
      484.24
    ],
    [
      559.26,
      282.21
    ],
    [
      505.76,
      178
    ]
  ],
  [
    [
      206.36,
      939.68
    ],
    [
      126.48,
      723.62
    ],
    [
      128.31,
      524.71
    ],
    [
      170.53,
      329.4
    ],
    [
      303.77,
      190.4
    ],
    [
      492.18,
      217.22
    ],
    [
      383.99,
      178
    ]
  ],
  [
    [
      417.57,
      1018.94
    ],
    [
      241.47,
      1008.27
    ],
    [
      123.25,
      848.67
    ],
    [
      104.59,
      674.06
    ],
    [
      190.32,
      526.07
    ],
    [
      216.39,
      353.09
    ],
    [
      364.58,
      201.32
    ],
    [
      558.43,
      221.41
    ],
    [
      438.93,
      178
    ]
  ],
  [
    [
      635.98,
      940.77
    ],
    [
      599.99,
      714.05
    ],
    [
      488.77,
      585.19
    ],
    [
      533.06,
      390.39
    ]
  ],
  [
    [
      515.61,
      844.74
    ],
    [
      602.57,
      667.55
    ],
    [
      611.67,
      468.27
    ],
    [
      465.65,
      291.78
    ],
    [
      239.07,
      306.77
    ],
    [
      283.2,
      178
    ]
  ],
  [
    [
      397.9,
      963.73
    ],
    [
      473.19,
      736.17
    ],
    [
      572.06,
      583.84
    ],
    [
      512.08,
      368.11
    ],
    [
      350.47,
      217.63
    ],
    [
      176.84,
      230.81
    ],
    [
      65.96,
      376.27
    ],
    [
      70,
      200.22
    ]
  ],
  [
    [
      645.22,
      957.09
    ],
    [
      559.16,
      805.54
    ],
    [
      431.4,
      683.59
    ],
    [
      206.21,
      718.93
    ],
    [
      76.67,
      607.43
    ],
    [
      84.27,
      411.37
    ],
    [
      70,
      204.28
    ]
  ],
  [
    [
      630.54,
      912.2
    ],
    [
      610.76,
      738.03
    ],
    [
      516.91,
      568.23
    ],
    [
      481.57,
      386.59
    ],
    [
      389.91,
      199.28
    ]
  ],
  [
    [
      185,
      905
    ],
    [
      81.68,
      655.55
    ],
    [
      81.68,
      385.55
    ],
    [
      185,
      138
    ],
    [
      434.45,
      241.32
    ],
    [
      489,
      178
    ]
  ]
];
